using System;

namespace LeaveManagement.Domain.Entities;

public class LeaveEntitlement
{
    public Guid Id { get; set; }
    public Guid EmployeeId { get; set; }
    public Employee? Employee { get; set; }
    public Guid AbsenceTypeId { get; set; }
    public AbsenceType? AbsenceType { get; set; }
    public int Year { get; set; }
    public int BaseDays { get; set; }
    public int AdditionalDays { get; set; }
    public int CarryOverDays { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    public int TotalEntitlement => BaseDays + AdditionalDays + CarryOverDays;
}
