// <auto-generated />
using System;
using LeaveManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeaveManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LeaveManagementDbContext))]
    [Migration("20260408115344_RefactorRoleUserAndCleanSeeding")]
    partial class RefactorRoleUserAndCleanSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AbsenceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RequesterEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalDaysRequested")
                        .HasColumnType("integer");

                    b.Property<string>("TreatingDoctor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequesterEmployeeId");

                    b.ToTable("AbsenceRequests");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DeductsFromBalance")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresDoctor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AbsenceTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = true,
                            Description = "Vacaciones anuales reglamentarias",
                            IsActive = true,
                            MaxDaysPerYear = 14,
                            Name = "Vacaciones",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CalculationType = "CalendarDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por enfermedad con certificado médico",
                            IsActive = true,
                            MaxDaysPerYear = 30,
                            Name = "Licencia Médica",
                            RequiresAttachment = true,
                            RequiresDoctor = true
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CalculationType = "CalendarDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por matrimonio (7 días consecutivos)",
                            IsActive = true,
                            MaxDaysPerYear = 7,
                            Name = "Matrimonio",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por fallecimiento de pariente directo (3 días laborables)",
                            IsActive = true,
                            MaxDaysPerYear = 3,
                            Name = "Fallecimiento Pariente",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por nacimiento (10 días laborables)",
                            IsActive = true,
                            MaxDaysPerYear = 10,
                            Name = "Nacimiento",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por cambio de residencia (1 día laborable)",
                            IsActive = true,
                            MaxDaysPerYear = 1,
                            Name = "Cambio de Residencia",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AbsenceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ApproverEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAfterAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceRequestId");

                    b.HasIndex("ApproverEmployeeId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AbsenceRequestId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceRequestId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Code = "RH",
                            IsActive = true,
                            Name = "Recursos Humanos"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Code = "IT",
                            IsActive = true,
                            Name = "Tecnología de la Información"
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            Code = "FIN",
                            IsActive = true,
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Code = "OPS",
                            IsActive = true,
                            Name = "Operaciones"
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-5555-5555-555555555555"),
                            Code = "SLS",
                            IsActive = true,
                            Name = "Ventas"
                        },
                        new
                        {
                            Id = new Guid("d6666666-6666-6666-6666-666666666666"),
                            Code = "LGL",
                            IsActive = true,
                            Name = "Legal"
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AN8")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.EmployeeSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("EmployeeSupervisors");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date", "CountryCode")
                        .IsUnique();

                    b.ToTable("PublicHolidays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d695a-f45b-7f2f-bdf4-84ea708ef9ab"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Año Nuevo",
                            Name = "Año Nuevo"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-765f-968c-3812fafe6cd7"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de Reyes",
                            Name = "Día de Reyes"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-75e6-8137-4775223b3f11"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de la Altagracia",
                            Name = "Día de la Altagracia"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7db2-a2f9-f8272fc4bb14"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de Duarte",
                            Name = "Día de Duarte"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-761f-b133-6d9b3e7bd5a0"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Independencia Nacional",
                            Name = "Independencia Nacional"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7719-abc1-0fe250e0aebc"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Viernes Santo",
                            Name = "Viernes Santo"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-74d4-9a30-20f6fd4d1274"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día del Trabajo",
                            Name = "Día del Trabajo"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7c16-9009-52cfb8b7720a"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corpus Christi",
                            Name = "Corpus Christi"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7144-b2ca-eb93d84cbf5f"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de la Restauración",
                            Name = "Día de la Restauración"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7084-88bc-07ef92442906"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de las Mercedes",
                            Name = "Día de las Mercedes"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7399-9b3d-2ba57d0d54e6"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de la Constitución",
                            Name = "Día de la Constitución"
                        },
                        new
                        {
                            Id = new Guid("019d695a-f45b-7361-a348-a3633406757e"),
                            CountryCode = "DO",
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de Navidad",
                            Name = "Día de Navidad"
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.VacationBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CarriedOverDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<int>("UsedDays")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year")
                        .IsUnique();

                    b.ToTable("VacationBalances");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceRequest", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceType", "AbsenceType")
                        .WithMany()
                        .HasForeignKey("AbsenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "RequesterEmployee")
                        .WithMany()
                        .HasForeignKey("RequesterEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("Employee");

                    b.Navigation("RequesterEmployee");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceType", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceRequest", null)
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("AbsenceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceRequest", "AbsenceRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("AbsenceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbsenceRequest");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId");

                    b.HasOne("LeaveManagement.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("LeaveManagement.Domain.Entities.Employee", "UserId");

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.EmployeeSupervisor", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("LeaveManagement.Domain.Entities.EmployeeSupervisor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.VacationBalance", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceRequest", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceType", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
