// <auto-generated />
using System;
using LeaveManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeaveManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LeaveManagementDbContext))]
    partial class LeaveManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AbsenceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalDaysRequested")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequesterEmployeeId");

                    b.ToTable("AbsenceRequests");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DeductsFromBalance")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresDoctor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AbsenceTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = true,
                            Description = "Vacaciones anuales reglamentarias",
                            IsActive = true,
                            MaxDaysPerYear = 14,
                            Name = "Vacaciones",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CalculationType = "CalendarDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por enfermedad con certificado médico",
                            IsActive = true,
                            MaxDaysPerYear = 30,
                            Name = "Licencia Médica",
                            RequiresAttachment = true,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por matrimonio (5 días laborables)",
                            IsActive = true,
                            MaxDaysPerYear = 5,
                            Name = "Matrimonio",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por fallecimiento de pariente directo (3 días laborables)",
                            IsActive = true,
                            MaxDaysPerYear = 3,
                            Name = "Fallecimiento Pariente",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CalculationType = "WorkingDays",
                            DeductsFromBalance = false,
                            Description = "Licencia por paternidad (2 días laborables)",
                            IsActive = true,
                            MaxDaysPerYear = 2,
                            Name = "Paternidad",
                            RequiresAttachment = false,
                            RequiresDoctor = false
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AbsenceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ApproverEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAfterAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceRequestId");

                    b.HasIndex("ApproverEmployeeId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AbsenceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AbsenceRequestId1")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceRequestId");

                    b.HasIndex("AbsenceRequestId1");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Code = "RH",
                            IsActive = true,
                            Name = "Recursos Humanos"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Code = "IT",
                            IsActive = true,
                            Name = "Tecnología de la Información"
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            Code = "FIN",
                            IsActive = true,
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Code = "OPS",
                            IsActive = true,
                            Name = "Operaciones"
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-5555-5555-555555555555"),
                            Code = "SLS",
                            IsActive = true,
                            Name = "Ventas"
                        },
                        new
                        {
                            Id = new Guid("d6666666-6666-6666-6666-666666666666"),
                            Code = "LGL",
                            IsActive = true,
                            Name = "Legal"
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            DepartmentId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Email = "juan.perez@example.do",
                            EmployeeCode = "EMP001",
                            FirstName = "Juan",
                            HireDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastName = "Pérez",
                            NationalId = "001-0000000-1",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.EmployeeSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("EmployeeSupervisors");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Year")
                        .IsUnique();

                    b.ToTable("PublicHolidays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Año Nuevo",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            Date = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de Reyes",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000003"),
                            Date = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de la Altagracia",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000004"),
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de Duarte",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000005"),
                            Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Independencia Nacional",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000006"),
                            Date = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Viernes Santo",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000007"),
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día del Trabajo",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000008"),
                            Date = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corpus Christi",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000009"),
                            Date = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de la Restauración",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-00000000000a"),
                            Date = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de las Mercedes",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-00000000000b"),
                            Date = new DateTime(2026, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de la Constitución",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-00000000000c"),
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Día de Navidad",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActiveDirectoryObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDirectoryObjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.VacationBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CarriedOverDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<int>("UsedDays")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year")
                        .IsUnique();

                    b.ToTable("VacationBalances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CarriedOverDays = 0,
                            EmployeeId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            ExpiresAt = new DateTime(2027, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalDays = 14,
                            UsedDays = 0,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceRequest", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceType", "AbsenceType")
                        .WithMany()
                        .HasForeignKey("AbsenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "RequesterEmployee")
                        .WithMany()
                        .HasForeignKey("RequesterEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AbsenceType");

                    b.Navigation("Employee");

                    b.Navigation("RequesterEmployee");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceType", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceRequest", null)
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("AbsenceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("AbsenceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.AbsenceRequest", "AbsenceRequest")
                        .WithMany()
                        .HasForeignKey("AbsenceRequestId1");

                    b.Navigation("AbsenceRequest");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("LeaveManagement.Domain.Entities.Employee", "UserId");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.EmployeeSupervisor", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("LeaveManagement.Domain.Entities.EmployeeSupervisor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.VacationBalance", b =>
                {
                    b.HasOne("LeaveManagement.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceRequest", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("LeaveManagement.Domain.Entities.AbsenceType", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
